### ISSUE TITLE
UTF-8 encoded file with byte-order-marker cannot be parsed

### ISSUE THREAD

**Issue by jepler** [mgedmin/findimports#15]
```
$ python3 -c 'with open("example.py", "wb") as f: f.write("\ufeffimport sys\n".encode("utf-8"))'
$ file example.py
example.py: UTF-8 Unicode (with BOM) text
$ python3 example.py  # succeeds, producing no output
$ findimports example.py 
Traceback (most recent call last):…
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "example.py", line 1
    import sys
          ^
SyntaxError: invalid character in identifier
```

**Comment by mgedmin** [comment]
The fix would be to use `tokenize.open()` instead of builtin `open()` in `find_imports()` and `find_imports_and_track_names()`.

This is somewhat complicated by `tokenize.open()` not existing in Python 2.7, for which I propose a simple solution: drop 2.7 support, it's been long enough.

I would also like to have a regression test for this, which ought to be simple enough (create a sample file containing a BOM in tests/sample-tree/, add a doctest file, ugh, I hate doctests, why did past me write so many of them?).

I am tired.  A PR would be helpful in getting this fixed sooner.
